### ISSUE TITLE
The shallowWithIntl is throwing error `TypeError: n.getChildContext is not a function`

### ISSUE THREAD

**Issue by Dr-KiranJogu** [formatjs/react-intl#1557]
When I am running unit tests with latest react-intl version , The shallowWithIntl is throwing error `TypeError: n.getChildContext is not a function`. 
But they are working fine with react-intl version 2.9.0

### Expected behavior

The shallowWithIntl should not throw any error with latest react-intl version.

### Current behavior

When I am running unit tests with latest react-intl version , The shallowWithIntl is throwing error `TypeError: n.getChildContext is not a function`. 
### Your Environment

OS: MAC

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | 3.11.0 |
|      `npm ls react` | 16.12.0 |
|     `npm --version` | 5.6.0 |
|    `node --version` | v8.9.4 |

| OS   | Version |
| macOS Sierra | 10.12.3 |
| NAME | VERSION |

| Browser | Version |
| ------- | ------- |
| NAME    | VERSION |

**Comment by longlho** [comment]
do you have codesandbox URLs? Did you follow https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md?
