### ISSUE TITLE
Module '"react-intl"' has no exported member 'createIntl'

### ISSUE THREAD

**Issue by ntelkedzhiev** [formatjs/react-intl#1436]
I keep getting the missing export error after upgrading to 3.1.9 (from 2.8.0):

```
error TS2305: Module '"react-intl"' has no exported member 'createIntl'.
```

### Your Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | VERSION |
|      `npm ls react` | VERSION |
|     `npm --version` | VERSION |
|    `node --version` | VERSION |

| OS   | Version |
| ---- | ------- |
| NAME | VERSION |

| Browser | Version |
| ------- | ------- |
| NAME    | VERSION |

**Comment by ntelkedzhiev** [comment]
Never mind. Found the issue elsewhere.

**Comment by vesground** [comment]
What was your cause ?

**Comment by demonzoo** [comment]
> What was your cause ?

I had the same issue, but then I realized I was using an older version of '@types/react-intl'. After upgrading it to 3.0 version, the issue was gone, as you can see the useIntl function defined in the types.d.ts file.
